version: "3.4"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: test2
    networks:
      - sausage-store
    expose:
      - "8090"
    healthcheck:
      test: "curl -f http://localhost || false"
      interval: 20s
      timeout: 5s
      start_period: 40s
      retries: 5
  #green:
    #<<: *b
    #container_name: green
    #ports:
    #  - "8082:8082"
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      DB: ${DB}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: test2
    networks:
      - sausage-store

networks:
  sausage-store:
