version: "3.4"

services:
  blue: &backend
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend:latest
    restart: always
    container_name: blue
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"  
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6    
  green:
    <<: *backend
    container_name: green
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend-report:latest
    restart: always
    container_name: sausage-backend-report
    environment:
      DB: ${DB}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-frontend:latest
    restart: always
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
