version: "3.4"

services:
  blue: &b
    build:
      context: backend
      dockerfile: Dockerfile
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend:latest
    container_name: blue
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: test2
    networks:
      - sausage-store
    #expose:
    #  - "8081"
    #healthcheck:
    # test: curl --fail -s http://localhost:8081/actuator/health
    #  interval: 30s
    #  timeout: 10s
    #  start_period: 20s
    #  retries: 6    
  green:
    <<: *b
    container_name: green
  backend-report:
    build:
      context: backend-report
      dockerfile: Dockerfile
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    environment:
      DB: ${DB}
    networks:
      - sausage-store
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: test2
    networks:
      - sausage-store

networks:
  sausage-store:
